; Generated by Chef for <%= node[:fqdn] %>
; Local modifications will be overwritten.

(setq load-path (cons "/usr/local/Cellar/go/1.2/libexec/misc/emacs" load-path))
(require 'go-mode-load)

(setq auto-mode-alist (cons '("\\.go" . go-mode) auto-mode-alist))

(add-hook 'go-mode-hook
          (lambda ()
             (add-hook 'local-write-file-hooks
                        '(lambda()
                           (save-excursion
                             (delete-trailing-whitespace))))
             (set (make-local-variable 'tab-width) 2)
             (set (make-local-variable 'indent-tabs-mode) 't)))
