; Generated by Chef for <%= node[:fqdn] %>
; Local modifications will be overwritten.

(vendor 'jade-mode)

(require 'sws-mode)
(require 'jade-mode)
(add-to-list 'auto-mode-alist '("\\.styl$" . sws-mode))
(add-to-list 'auto-mode-alist '("\\.jade$" . jade-mode))
